spring.application.name=earthquake_backend
server.port=9090
# Database
spring.datasource.url=jdbc:postgresql://localhost:5440/earthquake_db
spring.datasource.username=admin
spring.datasource.password=admin
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# CORS
app.cors.allowed-origins=http://localhost:5173
# USGS
app.usgs.url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson
app.usgs.default-hours-back=24
